version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tripwith-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} #
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: tripwith-api
    restart: always
    depends_on:
      - mysql
    env_file: .env # ✅ .env 파일 로드
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      FRONT_PORT: ${FRONT_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '8000:8000'
    command: ['node', 'dist/main.js']

volumes:
  mysql_data:
